name: Build and Push to cachix

on:
  push:
  workflow_dispatch:

jobs:
  build-packages:
    strategy:
      # Continue with the remaining packages if one fails
      fail-fast: false

      matrix:
        os:
          - ubuntu-latest # x86_64-linux
          - ubuntu-24.04-arm # aarch64-linux
          - macos-latest # aarch64-darwin

        package:
          - aim

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v16
        with:
          name: "${{ secrets.CACHIX_CACHE_NAME }}"
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix --accept-flake-config build .#${{ matrix.package }}

  build-nixos-configuration:
    strategy:
      fail-fast: false # Continue with the remaining packages if one fails

      matrix:
        conf:
          - os: ubuntu-24.04-arm
            host: yzx9-rpi5

    runs-on: ${{ matrix.conf.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v16
        with:
          name: "${{ secrets.CACHIX_CACHE_NAME }}"
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix --accept-flake-config build .#nixosConfigurations.${{matrix.conf.host}}.config.system.build.toplevel
